language: node_js
dist: trusty
sudo: false

node_js:
  # Use the explicit NodeJS LTS version 8.9.4 to avoid any automatic upgrade of the version.
  # This ensures that all Travis jobs run consistently and don't have different Node versions.
  - '9.8.0'

branches:
   only:
      - master

before_script:
  - cd src
  - npm install -g @angular/cli

script:
  - npm run build:prod

cache:
  directories:
    - ./node_modules/
